### ISSUE TITLE
LSP Lua/C/Rust: Error in plugin_view:325

### ISSUE THREAD

**Issue by ShalokShalom** [pragtical/plugin-manager#2]
When I try to 'View Source' for one of the LSP clients, my log says: 

![Screenshot_20230923_150609](https://github.com/pragtical/plugin-manager/assets/6344099/1c2859ec-ccd9-4c19-b8df-09d3a5ec3c00)

I am on the current git builds from both the editor and package manager. 
Garuda Arch

**Comment by jgmdev** [comment]
Just in case I fixed a related issue directly on our fork, submitted fix to upstream here: lite-xl/lite-xl-plugin-manager#46

**Comment by ShalokShalom** [comment]
Do you think its safe to close this?

**Comment by jgmdev** [comment]
I guess, it should properly show a message that plugin source could not be found (which is the case of meta plugins, etc...)
