### ISSUE TITLE
MacBook M1 install error

### ISSUE THREAD

**Issue by sprainbrains** [pragtical/plugin-manager#3]
> Fri Dec 1 18:26:24 2023 [ERROR] error running /Applications/Pragtical.app/Contents/Resources/plugins/plugin_manager/ppm.aarch64-darwin install evergreen:0.2 --json --mod-version=3.3.0 --quiet --progress --userdir=/Users/nicksin/.config/pragtical --datadir=/Applications/Pragtical.app/Contents/Resources --binary=/Applications/Pragtical.app/Contents/MacOS/pragtical --assume-yes: {"error":"src/ppm.lua:887: src/ppm.lua:887: src/ppm.lua:880: Addon tree-sitter-lua does not support arch aarch64-darwin","actions":["Installing complex library tree-sitter-lua."],"warnings":["console stub on https://github.com/pragtical/plugins.git:master has differing version from remote (0.2 vs 0.1); may lead to install being inconsistent"]}
at ...l.app/Contents/Resources/plugins/plugin_manager/init.lua:125
stack traceback:
...l.app/Contents/Resources/plugins/plugin_manager/init.lua:125: in function <...l.app/Contents/Resources/plugins/plugin_manager/init.lua:98>
[C]: in function 'xpcall'
...lications/Pragtical.app/Contents/Resources/core/init.lua:1097: in function <...lications/Pragtical.app/Contents/Resources/core/init.lua:1095>

Tried to install evergreen plugin in Pragtical on my M1 MacBook. So..it's failed.
Pragtical 3.2.0, arm64

**Comment by jgmdev** [comment]
Whoops, that was a mistake from my side when adding the manifest.json file to the repo and forgetting to set correct arch to aarch64-darwin, this commit should fix it https://github.com/pragtical/evergreen/commit/155af495bbed89dab91c96da08095c1254e88c15 I hope I didn't made any more manifest mistakes...

If the change isn't reflected on your side close pragtical, then `rm -rf ~/.config/pragtical/ppm/`, relaunch the editor and try again.

**Comment by sprainbrains** [comment]
> > 
> 
> > If the change isn't reflected on your side close pragtical, then `rm -rf ~/.config/pragtical/ppm/`, relaunch the editor and try again.
> 
> Thx! it's helped.
> 
> But I got another issue - critical down app. (before I installed evergreen plugin)
> 
> ```
> -------------------------------------
> Translated Report (Full Report Below)
> -------------------------------------
> 
> Process:               pragtical [55525]
> Path:                  /Applications/Pragtical.app/Contents/MacOS/pragtical
> Identifier:            dev.pragtical
> Version:               3.2.0-jit (???)
> Code Type:             ARM-64 (Native)
> Parent Process:        launchd [1]
> User ID:               501
> 
> Date/Time:             2023-12-08 15:21:02.8108 +0300
> OS Version:            macOS 14.1.2 (23B92)
> Report Version:        12
> Anonymous UUID:        221424D0-7E38-7062-B2D9-E71D0C8803C0
> 
> Sleep/Wake UUID:       DA508772-A093-49D0-A5C1-9D89095E0855
> 
> Time Awake Since Boot: 270000 seconds
> Time Since Wake:       11695 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes:       KERN_INVALID_ADDRESS at 0x0000800000000009 -> 0x0000000000000009 (possible pointer authentication failure)
> Exception Codes:       0x0000000000000001, 0x0000800000000009
> 
> Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
> Terminating Process:   exc handler [55525]
> 
> VM Region Info: 0x9 is not in any region.  Bytes before following region: 68719476727
>      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
>      UNUSED SPACE AT START
> --->  
>      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)
> 
> Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
> 0   pragtical                     	       0x100f44f74 0x100eac000 + 626548
> 1   pragtical                     	       0x100eebf10 0x100eac000 + 261904
> 2   ltreesitter.so                	       0x10f7e6ecc luaopen_ltreesitter + 76
> 3   ltreesitter.so                	       0x10f7e6f58 luaopen_lite_xl_ltreesitter + 32
> 4   pragtical                     	       0x100eb6c8c 0x100eac000 + 44172
> 5   pragtical                     	       0x100ed4420 0x100eac000 + 164896
> 6   pragtical                     	       0x100ee1ce4 0x100eac000 + 220388
> 7   pragtical                     	       0x100ed4420 0x100eac000 + 164896
> 8   pragtical                     	       0x100ee1ce4 0x100eac000 + 220388
> 9   pragtical                     	       0x100ed4420 0x100eac000 + 164896
> 10  pragtical                     	       0x100ee1ce4 0x100eac000 + 220388
> 11  pragtical                     	       0x100ed4420 0x100eac000 + 164896
> 12  pragtical                     	       0x100eec69c 0x100eac000 + 263836
> 13  pragtical                     	       0x100eccfec 0x100eac000 + 135148
> 14  dyld                          	       0x1834bd0e0 start + 2360
> 
> Thread 1:
> 0   libsystem_pthread.dylib       	       0x183833e28 start_wqthread + 0
> 
> Thread 2:
> 0   libsystem_pthread.dylib       	       0x183833e28 start_wqthread + 0
> 
> Thread 3:
> 0   libsystem_pthread.dylib       	       0x183833e28 start_wqthread + 0
> 
> Thread 4:
> 0   libsystem_pthread.dylib       	       0x183833e28 start_wqthread + 0
> 
> Thread 5:: CVDisplayLink
> 0   libsystem_kernel.dylib        	       0x1837fc0ac __psynch_cvwait + 8
> 1   libsystem_pthread.dylib       	       0x183839628 _pthread_cond_wait + 1272
> 2   CoreVideo                     	       0x18c1d3528 CVDisplayLink::waitUntil(unsigned long long) + 328
> 3   CoreVideo                     	       0x18c1d25f4 CVDisplayLink::runIOThread() + 504
> 4   libsystem_pthread.dylib       	       0x183839034 _pthread_start + 136
> 5   libsystem_pthread.dylib       	       0x183833e3c thread_start + 8
> 
> Thread 6:: process_kill
> 0   libsystem_kernel.dylib        	       0x1837fc0ac __psynch_cvwait + 8
> 1   libsystem_pthread.dylib       	       0x1838395fc _pthread_cond_wait + 1228
> 2   pragtical                     	       0x100fb1968 0x100eac000 + 1071464
> 3   pragtical                     	       0x100eba394 0x100eac000 + 58260
> 4   pragtical                     	       0x100fb1460 0x100eac000 + 1070176
> 5   pragtical                     	       0x100fb1fb4 0x100eac000 + 1073076
> 6   libsystem_pthread.dylib       	       0x183839034 _pthread_start + 136
> 7   libsystem_pthread.dylib       	       0x183833e3c thread_start + 8
> 
> 
> Thread 0 crashed with ARM Thread State (64-bit):
>    x0: 0x00000001134c8380   x1: 0x00007fffffffffff   x2: 0x000000011357e690   x3: 0x0000000000000040
>    x4: 0x0000000000000067   x5: 0x0000000000000067   x6: 0x0000000000000074   x7: 0x0000000000000730
>    x8: 0xffffffffffffffff   x9: 0x000000011357eb18  x10: 0x00000001197bce70  x11: 0x0000000000000000
>   x12: 0x0000000000000000  x13: 0x00000001197bcde0  x14: 0x0000000000000018  x15: 0xfffd8001134cc988
>   x16: 0x0000000183865210  x17: 0x0000000000000004  x18: 0x0000000000000000  x19: 0x00000001134c8380
>   x20: 0x00007fffffffffff  x21: 0x000000011357e690  x22: 0x000000011357e6a0  x23: 0x00000001134c8380
>   x24: 0xfff9000000000000  x25: 0x00000000fff90000  x26: 0xffffffffffffffff  x27: 0x000000011357e6e0
>   x28: 0x000000011357e650   fp: 0x000000016ef52130   lr: 0x0000000100eebf10
>    sp: 0x000000016ef52100   pc: 0x0000000100f44f74 cpsr: 0x20001000
>   far: 0x0000800000000009  esr: 0x92000044 (Data Abort) byte write Translation fault
> 
> Binary Images:
>       0x10f7e0000 -        0x10f813fff ltreesitter.so (*) <72f2ebf2-1805-31c8-8b72-3c11df5555a8> /Users/USER/*/ltreesitter.so
>       0x101724000 -        0x10178ffff com.apple.AppleMetalOpenGLRenderer (1.0) <227d0ea7-67f7-36da-949b-01c1f245b799> /System/Library/Extensions/AppleMetalOpenGLRenderer.bundle/Contents/MacOS/AppleMetalOpenGLRenderer
>       0x10145c000 -        0x101467fff libobjc-trampolines.dylib (*) <c9ce7923-2f2d-31eb-a6e4-0f3b7a78f895> /usr/lib/libobjc-trampolines.dylib
>       0x100eac000 -        0x1011bbfff dev.pragtical (3.2.0-jit) <64cdf526-30e5-3f30-806d-358ee8515860> /Applications/Pragtical.app/Contents/MacOS/pragtical
>       0x1834b7000 -        0x18354b317 dyld (*) <ec7a3ba0-f9bf-3ab8-a0f4-8622e5606b20> /usr/lib/dyld
>               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
>       0x183864000 -        0x18386affb libsystem_platform.dylib (*) <fc8cd17b-8769-348c-8dcd-1bfed022f9e4> /usr/lib/system/libsystem_platform.dylib
>       0x183832000 -        0x18383eff3 libsystem_pthread.dylib (*) <daf95373-5de6-39a1-a6ce-d87f3f0629cc> /usr/lib/system/libsystem_pthread.dylib
>       0x1837f7000 -        0x183831fef libsystem_kernel.dylib (*) <b7751381-1442-30b5-91b9-ad7be461bebe> /usr/lib/system/libsystem_kernel.dylib
>       0x18c1d0000 -        0x18c22dfff com.apple.CoreVideo (1.8) <e392a14b-42a2-3376-a46b-e7ff0aa4c272> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
> 
> External Modification Summary:
>  Calls made by other processes targeting this process:
>    task_for_pid: 0
>    thread_create: 0
>    thread_set_state: 0
>  Calls made by this process:
>    task_for_pid: 0
>    thread_create: 0
>    thread_set_state: 0
>  Calls made by all processes on this machine:
>    task_for_pid: 0
>    thread_create: 0
>    thread_set_state: 0
> 
> VM Region Summary:
> ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)
> Writable regions: Total=467.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=467.5M(100%)
> 
>                                VIRTUAL   REGION 
> REGION TYPE                        SIZE    COUNT (non-coalesced) 
> ===========                     =======  ======= 
> Activity Tracing                   256K        1 
> ColorSync                          608K       28 
> CoreAnimation                       16K        1 
> CoreGraphics                        16K        1 
> Dispatch continuations            64.0M        1 
> Foundation                          16K        1 
> Kernel Alloc Once                   32K        1 
> MALLOC                           325.0M       40 
> MALLOC guard page                  192K       12 
> MALLOC_LARGE (reserved)           63.3M        2         reserved VM address space (unallocated)
> OpenGL GLSL                        256K        3 
> STACK GUARD                       56.1M        7 
> Stack                             11.2M        7 
> VM_ALLOCATE                       3536K       36 
> __AUTH                             902K      197 
> __AUTH_CONST                      14.7M      359 
> __CTF                               824        1 
> __DATA                            3820K      349 
> __DATA_CONST                      18.0M      364 
> __DATA_DIRTY                       915K      114 
> __FONT_DATA                          4K        1 
> __GLSLBUILTINS                    5174K        1 
> __LINKEDIT                       886.8M        5 
> __OBJC_RO                         70.8M        1 
> __OBJC_RW                         2156K        1 
> __TEXT                           296.7M      378 
> dyld private memory                272K        2 
> mapped file                      161.6M       20 
> shared memory                      848K       13 
> ===========                     =======  ======= 
> TOTAL                              1.9G     1947 
> TOTAL, minus reserved VM space     1.9G     1947 
> ```

solved it. Delete plugin from config, fetching again and  install from plugin manager again.

**Comment by jgmdev** [comment]
Thanks for reporting!
