### ISSUE TITLE
[windows] Installation break in latest/continues build ppm

### ISSUE THREAD

**Issue by maksimaliabyshev** [pragtical/plugin-manager#6]
continues build ppm
```
scoop install https://gist.githubusercontent.com/maksimaliabyshev/6b311f327078022dd365eea96f2428e8/raw/pragtical-plugin-manager.json --global
ppm --version                                                                                                                                
1.0.2-309-gba088dc-x86_64-windows
```
command in powershell
```powershell
    ppm install align_carets autoinsert autowrap bracketmatch codeplus colorpicker colorpreview console copyfilelocation custom_caret `
        datetimestamps editorconfig evergreen endwise eofnewline ephemeral_tabs eval exec exterm extend_selection_line force_syntax formatter `
        gitblame gitdiff_highlight gitopen gitstatus gui_filepicker indent_convert indentguide json jsonmod `
        keymap_export linenumbers link_opener lintplus lorem markers minimap motiontrail navigate openfilelocation openselected `
        profiler rainbowparen recentfiles regexreplacepreview restoretabs scalestatus scm selectionhighlight smartopenselected smoothcaret `
        sort sortcss spellcheck sticky_scroll su_save svg_screenshot tab_switcher tabnumbers terminal texcompile titleize `
        todotreeview togglesnakecamel treeview-extender typingspeed wordcount --assume-yes --progress
```
![image](https://github.com/user-attachments/assets/c06f786a-6367-43d3-ac94-4e12bda1df6f)

**Comment by jgmdev** [comment]
Same issue as in pragtical/lsp#14 of needing to add `--datadir='C:\ProgramData\scoop\apps\pragtical\current\data'` for the plugin manager to find core plugins in order to meet the requirements.

**Comment by maksimaliabyshev** [comment]
1. exterm - terminate the installer
2. `--datadir='C:\ProgramData\scoop\apps\pragtical\current\data'` - not work, installation takes place in the user's directory, not in `--datadir`.

**Comment by jgmdev** [comment]
> 1. exterm - terminate the installer

Tested locally with what you shared and the --datadir flag set to pragtical data path and installation was successful:

```sh
ppm install align_carets autoinsert autowrap bracketmatch codeplus colorpicker colorpreview
console copyfilelocation custom_caret datetimestamps editorconfig evergreen endwise 
eofnewline ephemeral_tabs eval exec exterm extend_selection_line force_syntax formatter 
gitblame gitdiff_highlight gitopen gitstatus gui_filepicker indent_convert indentguide json 
jsonmod keymap_export linenumbers link_opener lintplus lorem markers minimap 
motiontrail navigate openfilelocation openselected profiler rainbowparen recentfiles 
regexreplacepreview restoretabs scalestatus scm selectionhighlight smartopenselected 
smoothcaret sort sortcss spellcheck sticky_scroll su_save svg_screenshot tab_switcher 
tabnumbers terminal texcompile titleize todotreeview togglesnakecamel treeview-extender 
typingspeed wordcount --datadir='C:\ProgramData\scoop\apps\pragtical\current\data' 
--assume-yes --progress
```
Everything installed inside `C:\Users\<user>\.config\pragtical`

> 2\. `--datadir='C:\ProgramData\scoop\apps\pragtical\current\data'` - not work, installation takes place in the user's directory, not in `--datadir`.

This flag is to tell the plugin manager where are the core files and plugins, not to install inside of that directory. (if I got you correctly and that is what you mean)

**Comment by jgmdev** [comment]
So I see that scoop adds `C:\ProgramData\scoop\shims` to path and install some wrapper executables that redirect to real app installation path, this is the cause for the plugin manager failing to find the data files, since the `pragtical.exe` redirector binary stored on `C:\ProgramData\scoop\shims` is not sitting along side the core lua runtime files. 

Besides using --datadir another work around would be prepending C:\ProgramData\scoop\apps\pragtical\current\ to PATH environment variable so the plugin manager is able to properly find the data directory. This way you wouldn't need to specify --datadir each time.

**Comment by jgmdev** [comment]
Added solution to plugins troubleshooting section of website:

https://pragtical.dev/docs/user-guide/plugins#ppm-installed-from-scoop-fails-to-install-plugins
